### ISSUE TITLE
undefined method `latitude' with mongoid? :(

### ISSUE THREAD

**Issue by solars** [apneadiving/Google-Maps-for-Rails#148]
Hey there,

I have the following setup: https://gist.github.com/ca87897568f382dad0f5
using mongoid_spacial

with the object:
 => "#<Spot _id: 4f3182b937db5f1e51000001, _type: nil, name: \"p 1\", location: [9.744417, 47.413417]>"

and generated indexes, I suddenly get:
undefined method `latitude' for #Spot:0x000000057f35c8

and have no idea why...
I've upgraded the gems to the latest version .. can anyone tell me whats wrong with that?
I'm a bit confused about whats needed now in the model and what isn't..

**Comment by FarihulR** [comment]
undefined method `latitude' for #Lapor:0x007f272fd37e00
then  i have add source at model  but not showing location google map
def latitude
  location[0]
end

def longitude
  location[1]
end
