### ISSUE TITLE
[2¢ suggestion] Static Map for printing

### ISSUE THREAD

**Issue by clm-a** [apneadiving/Google-Maps-for-Rails#150]
Hi again :)

Having :

``` erb
<%= static_gmaps(data_hash) %>
```

as an in-place alternative to

``` erb
<%= gmaps(data_hash) %>
```

returning an img_tag calling  Static Map Api with tailored arguments, would allow us to print a map --- with, for example, user-persisted elements.

I would love trying to implement something like that. Would you consider any pull request with this feature ? -- Or did I miss a similar feature ? :-)

**Comment by chrise86** [comment]
Was this ever implemented?

**Comment by apneadiving** [comment]
@chrise86 nope it wasnt, btw the api has changed a lot since @clm-a suggested to implement that
