### ISSUE TITLE
Error: Uncaught ReferenceError: MarkerClusterer is not defined

### ISSUE THREAD

**Issue by ryanjones** [apneadiving/Google-Maps-for-Rails#166]
Seem to still get this error if do_clustering isn't set. Not a big deal since I can just set it. 

gmaps4rails (1.4.8) 

No error:
:markers     => { :data => gmap_prepare_homes(@homes), :options => { :do_clustering => false } })

Error: Uncaught ReferenceError: MarkerClusterer is not defined
:markers     => { :data => gmap_prepare_homes(@homes) })
:markers     => { :data => gmap_prepare_homes(@homes), :options => {  } })

gmap_prepare_homes is a helper that calls to_gmaps4rails and sets up some pin pictures. Full code:

=gmaps(:map_options => { :center_latitude => @search.search_pin.nil? ? Search::EDMONTON_GEO[:lat] : @search.search_pin["lat"],  :center_longitude => @search.search_pin.nil? ? Search::EDMONTON_GEO[:lng] : @search.search_pin["lng"],  :zoom => @search.search_pin.nil? ? 11 : 12}, :markers     => { :data => gmap_prepare_dayhomes(@homes), :options => { } })

**Comment by stevenm** [comment]
Im showing the same error recently

Bundle complete! 29 Gemfile dependencies, 126 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
ste (master) $ rails generate gmaps4rails:install
Could not find generator 'gmaps4rails:install'. Maybe you meant 'gmaps4rails:copy_js' or 'gmaps4rails:copy_coffee' or 'jquery:datatables:install'
Run `rails generate --help` for more options.
ste (master) $ bundle show gmaps4rails
/usr/local/rvm/gems/ruby-2.3.0/gems/gmaps4rails-2.1.2

Would aprreciate a pointer or thoughts ?

**Comment by stevenm** [comment]
RESOLVED

Google moved the resource to Git hub, changed the link to JS too

https://cdn.rawgit.com/googlemaps/js-marker-clusterer/gh-pages/src/markerclusterer.js
