### ISSUE TITLE
Rich marker seems to be undefined

### ISSUE THREAD

**Issue by andrea-ale-sbarra** [apneadiving/Google-Maps-for-Rails#329]
In model I define this method (as specified in doc) 
    def gmaps4rails_marker_picture
        {"rich_marker" =>  "<div class='my-marker'>It works!<img height='30' width='30' src='http://farm4.static.flickr.com/3212/3012579547_097e27ced9_m.jpg'/></div>"} end

But in the page i got this error: **Uncaught ReferenceError: RichMarker is not defined**

Can't figure it out

**Comment by amitojha01** [comment]
I have the same issue
