### ISSUE TITLE
uninitialized constant ::Gmaps4rails

### ISSUE THREAD

**Issue by sharmaansh21** [apneadiving/Google-Maps-for-Rails#442]
I am using rails 4 and gem 'gmaps4rails', 
in controller 

@hash = ::Gmaps4rails.build_markers(@lessons) do |lesson, marker|
      marker.lat lesson.latitude
      marker.lng lesson.longitude
      marker.infowindow lesson.description
    end

On development it is working fine but on production
NameError (uninitialized constant Gmaps4rails):

On production
Using gmaps4rails 2.1.2

**Comment by zachalewel** [comment]
Restarting the server also fixed the issue for me too. Thanks!
