### ISSUE TITLE
Uncaught ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by adham90** [apneadiving/Google-Maps-for-Rails#473]
google map don't load
and i have this error in my console
```
Uncaught ReferenceError: _ is not defined
```
this is my [repo](https://github.com/adham90/geekhub)
the map under **[profile show](https://github.com/adham90/geekhub/blob/master/app%2Fviews%2Fprofiles%2Fshow.html.haml)**

**Comment by apneadiving** [comment]
Follow instructions and add underscore.js

**Comment by adham90** [comment]
Ohh thanks, the file was corrupted :+1:
