### ISSUE TITLE
Attach custom data to markers

### ISSUE THREAD

**Issue by fabn** [apneadiving/Google-Maps-for-Rails#478]
I'm using the `MarkersBuilder` ruby helper to build some marker data and it's awesome, however I have an issue. In the [rubydoc](https://github.com/apneadiving/Google-Maps-for-Rails/blob/9388a062594f9ba5d8022f611284b4a7218782e9/lib/gmaps4rails/markers_builder.rb#L22) you attach custom data to the marker with this syntax:

```ruby
markers = Gmaps4rails.build_markers(collection) do |(code, state), marker|
  marker.lat state['latitude']
  marker.lng state['longitude']
  marker.title state['name']
  marker.json state: code, id: state.id # here are my custom data
end
```

What's that for? I'm adding markers to map using the handler:

```coffeescript
  addMarkers: (data)=>
    @deleteMarkers()
    @markers = @handler.addMarkers(data)
    # Here I'm attaching a custom click handler
    google.maps.event.addListener(m.getServiceObject(), 'click', @myClickHandler) for m in @markers

  myClickHandler: (evt) ->
    # How to get state code from the clicked marker???

  # Later
  $.getJSON(myUrl).done(@addMarkers)
```

In `myClickHandler` I don't know how to access the `code` and the `id` I stored in the ruby code for the clicked marker.

**Comment by plicjo** [comment]
Hey @fabn:

You can't use the `.addMarkers` method when you are building markers with custom data.

You have to build them by `map`.

You can check it out in the wiki here: https://github.com/apneadiving/Google-Maps-for-Rails/wiki/Adding-an-id-to-markers-and-access-them-later

**Comment by fabn** [comment]
Yes, I found out that. I've added this code to handle the situation:

```coffeescript
# Monkey patch after init to attach custom json to marker
Gmaps.Google.Builders.Marker.prototype.after_init = ->
  @serviceObject[k] = v for k,v of @args.data # Attacching data to already built marker
```

In this way I can attach custom data automatically with no restrictions

```ruby
markers = Gmaps4rails.build_markers(collection) do |item, marker|
  marker.json data: {id: item.id, foo: item.foo} # marker (serviceObject) will have a id and a foo properties
end
```

**Comment by plicjo** [comment]
Wow, that's clean!

Can we close this @apneadiving

**Comment by apneadiving** [comment]
@fabn nice way :)
@plicjo  here we go ;)
