### ISSUE TITLE
Clusterer doesn't work for markers with the same coordinates?

### ISSUE THREAD

**Issue by ben-gy** [apneadiving/Google-Maps-for-Rails#480]
Hey there,

gmaps4rails is great by the way - big thanks to everyone for their time committed to the project.

My issue - I've installed gmaps4rails and everything is working well, except for clustering for markers that share the same coordinates.

![screen shot 2015-05-11 at 1 07 12 am](https://cloud.githubusercontent.com/assets/6506968/7554808/1b3a2870-f77a-11e4-8594-21bbf44ce79e.png)

![screen shot 2015-05-11 at 1 07 23 am](https://cloud.githubusercontent.com/assets/6506968/7554810/2832e1fc-f77a-11e4-84dc-de9aa40d5363.png)

![screen shot 2015-05-11 at 1 06 23 am](https://cloud.githubusercontent.com/assets/6506968/7554812/31ed5b8c-f77a-11e4-9443-28719387b577.png)

Here's my code for generating the markers and map: 
```
<script type="text/javascript">
  window.setTimeout(function(){
    var handler;
    handler = Gmaps.build('Google', { markers: { maxRandomDistance: 5, do_clustering: true, clusterer_maxZoom: 20, clusterer_gridSize: 4, randomize: true } });
    handler.buildMap({
      provider: {
        disableDefaultUI: true,
        scrollwheel: false,
        zoomControl: true,
        streetViewControl: true,
        backgroundColor: '#B3D1FF'
      },
      internal: {
        id: 'map'
      }
    }, function() {
      var markers;
      markers = handler.addMarkers(<%=raw @marker.to_json %>); 
      handler.bounds.extendWith(markers);
      handler.map.centerOn({
        lat: -25,
        lng: 135
      });
      handler.getMap().setZoom(4);
    }, 200);
  });
</script>
```
Thanks in advance for your help :)

**Comment by apneadiving** [comment]
sorry, I'm not sure what you expect :)

**Comment by apneadiving** [comment]
btw, please provide the generated script if you'd like me to debug

**Comment by ben-gy** [comment]
Hey mate - thanks for the speedy response :)

I was expecting the clusterer to continue clustering at high zoom levels. Couldn't get that working, but I ended up passing paramters like this and it worked the way I wanted it to: 

Gmaps.build('Google', { markers: { randomize: true, maxRandomDistance: 10, clusterer: { maxZoom: 20, gridSize: 40 }}});

Thanks anyway - hopefully this helps anyone who runs into the same problem.
