### ISSUE TITLE
Periodic error - google.maps.events is undefined

### ISSUE THREAD

**Issue by mpwalsh8** [apneadiving/Google-Maps-for-Rails#482]
Periodically I get the following error and I cannot figure out why.  It doesn't happen every time but happens frequently enough that it is a problem and causes a mobile web app to hang.

TypeError: google.maps.event is undefined
listener: google.maps.event.addListener,

The other information Firebug displays is:

SyntaxError: expected expression, got end of script
http://localhost:3000/venues/2
Line 0

None of my Google searches have yielded anything meaningful.

**Comment by apneadiving** [comment]
only means google maps script fails to load
