### ISSUE TITLE
"Uncaught TypeError: gem_marker.clear is not a function" when running removeMarkers.

### ISSUE THREAD

**Issue by steve32** [apneadiving/Google-Maps-for-Rails#484]
I cannot remove markers from an already rendered map. Whenever I try to run `handler.removeMarkers` I get the error in the title. Adding markers works fine.

**Comment by apneadiving** [comment]
Show your code, my guess you dont provide objects to the function, just json

**Comment by steve32** [comment]
Thanks! I was getting confused reading a lot of outdated tips.
