### ISSUE TITLE
Marker position inconsistent in example app

### ISSUE THREAD

**Issue by rtomsmith** [apneadiving/Google-Maps-for-Rails#486]
In the gmaps example app (no local edits), I create a single user which results in setting the latitude/longitude position (35.1185868, -120.5907252). Displaying the map on the index page shows the single marker for that user. However, when you repeatedly reload the index page, the marker changes its position - it's usually within a 1-2 block radius, but it almost always moves. So what's wrong here - the example app, the library, Google? Any ideas? This is obviously not reliable and I need the markers to accurately show positions on the map.

Thanks.

**Comment by apneadiving** [comment]
I dont know which version is used there but I introduced a small random offset (its off by default now) because in most cases, people had vague addresses with only city names so markers overlapped.

Tell me which version you use so I can help you more

**Comment by rtomsmith** [comment]
The gem version being used is 2.1.0.

**Comment by apneadiving** [comment]
ok then just upgrade to 2.1.2 :)

**Comment by apneadiving** [comment]
FYI, was changed in this commit: https://github.com/apneadiving/Google-Maps-for-Rails/commit/f30654e66e4dccf9ef20d08969fe506a24f39d03

**Comment by rtomsmith** [comment]
wow - ok, thanks.
