### ISSUE TITLE
Gmaps.store is undefined

### ISSUE THREAD

**Issue by lessless** [apneadiving/Google-Maps-for-Rails#492]
Hello,
on the https://github.com/apneadiving/Google-Maps-for-Rails/wiki/Adding-an-id-to-markers-and-access-them-later page there is a suggestion to store markers in the `Gmaps.store` which seems to be undefined in the current version.
Should it be created by the developer like `Gmaps.store = {}`? If this is so I believe it's better to update documentation to avoid confusion. 
Thanks

**Comment by apneadiving** [comment]
Feel free to edit, I actually didnt even create this page :)
