### ISSUE TITLE
Uncaught ReferenceError: google is not defined

### ISSUE THREAD

**Issue by lessless** [apneadiving/Google-Maps-for-Rails#493]
Hello,
upon first page load there is an error and a warning in the console

```
Uncaught ReferenceError: google is not defined primitives.self-5b8a3a670839d76c06f9877827daa0d739b27f8d6ebd346d7fc6006819755e65.js:5 

Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.  js?v=3.13&amp;sensor=false&amp;libraries=geometry:8 
```

Here is probably a solution http://stackoverflow.com/questions/24297829/execute-write-on-doc-it-isnt-possible-to-write-into-a-document-from-an-asynchr

**Comment by apneadiving** [comment]
this is due to turbolinks I guess. Easiest solution would be to always include google scripts
