### ISSUE TITLE
Javascript-goodies wiki page has probably a problem

### ISSUE THREAD

**Issue by bricesanchez** [apneadiving/Google-Maps-for-Rails#498]
Hello @apneadiving,

By following this link on http://stackoverflow.com/questions/14054628/typeerror-gmaps-map-is-undefined

This wiki page seems it had been erased : 
https://github.com/apneadiving/Google-Maps-for-Rails/wiki/Javascript-goodies

Is it normal ? Here the diff :
https://github.com/apneadiving/Google-Maps-for-Rails/wiki/Javascript-goodies/_compare/83a2c51b54eb905508f6257363a0c6476d6cf133

By the way, thanks for your awesome work on this Gem !

**Comment by apneadiving** [comment]
Hi Brice,

Yes, this page referred to the 1.x, and is completely deprecated with the current 2.x

What do you need?

Ben

**Comment by bricesanchez** [comment]
Nothing special, i'm trying to figure out why i've these errors : 
```js
Uncaught TypeError: Cannot read property 'offsetWidth' of nullxk @ js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region=:70ll @ js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region=:78Map @ map.self.js?body=1:13build @ builder.self.js?body=1:9Gmaps.Objects.Handler.Handler.buildMap @ handler.self.js?body=1:18(anonymous function) @ application.self.js?body=1:95
handler.self.js?body=1:108 Uncaught TypeError: Cannot read property 'getServiceObject' of undefined
```
But i've not finished to inspect my code.

Thanks for your answer.
