### ISSUE TITLE
buildMap is not defined

### ISSUE THREAD

**Issue by faradzh** [apneadiving/Google-Maps-for-Rails#505]
Hello guys, I'm here to raise the issue I faced just after first implementation of gmaps4rails gem in my application. I've done the configuration according to docs and tutorial video on youtube, however smth creepy is going on when I try to customize markers and infoboxes. So, the questions is there anything changed since the version used in video tutorial so that I could bumped into this issue. The only functionality I was able to set up is typical markers distributed around the locations specified in my model and standard infoboxes. I'd really appreciate if you could guide me through customization of markers and most importantly infoboxes!

**Comment by apneadiving** [comment]
I dont know which tutorial you are talking about but the links on the homepage are still valid

**Comment by faradzh** [comment]
It appears I've figured it out myself. Currently I'm curious about another thing. Is that possible to trigger some javascript right in the infowindow? Suppose, I want to sell houses represented by markers on the map so a user has to be able to add that "house"  to the shopping cart. Do you think I can fulfill it?

**Comment by apneadiving** [comment]
@faradzh I did this once, so I know its possible, yet I dont have the code I used, sorry

**Comment by caitlinashtari** [comment]
Hey, @faradzh! How did you resolve the undefined buildMap issue? Currently struggling with the same.

**Comment by faradzh** [comment]
Hello there, It's been pretty long since I dealt with this issue so I
barely remember the exact solution. What it means is that the buildMap
function is not plugged in so that to be used by the script.
