### ISSUE TITLE
TypeError: a is null

### ISSUE THREAD

**Issue by krnaidas** [apneadiving/Google-Maps-for-Rails#506]
The map is not showing when i load the site. When inspected, i get this error.

Tried using the example

Head:
    <%= render 'layouts/gmaps' %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> 
    <%= yield :javascripts %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>

JS:

handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'one_marker'}}, function(){
  markers = handler.addMarkers([
    {
      lat: 0,
      lng: 0,
      picture: {
        url: "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
        width:  36,
        height: 36
      },
      infowindow: "hello!"
    }
  ]);
});

view:

<div style='width: 800px;'>
  <div id="one_marker" style='width: 800px; height: 400px;'></div>
</div>

**Comment by apneadiving** [comment]
Sorry I cant help with so little information.
All examples work fine on the live version here: http://apneadiving.github.io/

So I bet there is a rails config you missed but its not really part of the gem so I have to close the issue
