### ISSUE TITLE
Uncaught ReferenceError: Gmaps is not defined

### ISSUE THREAD

**Issue by knd** [apneadiving/Google-Maps-for-Rails#508]
I'm using `gmaps4rails 2.1.2`, and `Rails 4.2`, and followed the exact tutorial at readme page. Everything works ok on my local dev machine. However, when I deploy to AWS, it can't to initialize Gmaps.

On local dev machine:
<img width="1436" alt="screen shot 2016-03-16 at 11 06 54 am" src="https://cloud.githubusercontent.com/assets/1356620/13801775/da9e3bf2-eb67-11e5-8453-450fc5101431.png">

On production:
<img width="1431" alt="screen shot 2016-03-16 at 11 07 18 am" src="https://cloud.githubusercontent.com/assets/1356620/13801784/ebae2f42-eb67-11e5-8342-8b4da420104e.png">

I open the compressed application.js on production, and see that gmaps4rails scripts are included there. What could be the problem Gmaps can't be initialized?
<img width="1434" alt="screen shot 2016-03-16 at 11 08 13 am" src="https://cloud.githubusercontent.com/assets/1356620/13801801/146fec86-eb68-11e5-8e06-c7bdb42d00d7.png">

**Comment by apneadiving** [comment]
Weird...

What if you use the version in cdn?
https://cdnjs.cloudflare.com/ajax/libs/gmaps4rails/2.1.2/gmaps4rails.min.js

**Comment by apneadiving** [comment]
@knd I'm curious to know what was the problem

**Comment by knd** [comment]
@apneadiving I moved from Rails 3 to Rails 4 so there was something different in asset pipeline settings.  Thank you for your reply.

**Comment by FutoRicky** [comment]
@knd what did you have to change? Having the same issue, currently on Rails 4
