### ISSUE TITLE
Where do i put API key for google maps?

### ISSUE THREAD

**Issue by jweinst1** [apneadiving/Google-Maps-for-Rails#510]
So I am trying to set up the basic map from the README in one of my views, but I am having trouble with two things.

1. Where do i put my API key to allow the API from google maps to be called?

2. On step 5, in the README, where in the rails app should that JS code be put?

Thanks!

**Comment by apneadiving** [comment]
Hi Josh,

Please ask questions on stackoverflow.
Paste the link here if you want.

Thanks

Benjamin
