### ISSUE TITLE
Map totally broken

### ISSUE THREAD

**Issue by RoccStar** [apneadiving/Google-Maps-for-Rails#512]
Map was working on my site yesterday, now broken. Also not working on the demo site http://apneadiving.github.io/.

**Comment by lucasgerard** [comment]
Might be the same problem: everything was working fine today, no code changed and my map is suddenly broken the following error `MarkerWithLabel is not defined`

**Comment by carnash-oz** [comment]
Same problem, yesterday (11-May) was fine, maybe some update.
Here is the console log from Chrome

GET http://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js 

GET http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js 404 (Not Found)
GET http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.9/src/markerclusterer_packed.js 
underscore.js:1548 
Uncaught ReferenceError: MarkerClusterer is not definedGmaps.Google.Primitives @ underscore.js:1548
Gmaps.Objects.Handler.Handler.setPrimitives @ underscore.js:1548
Handler @ underscore.js
Gmaps.build @ underscore.js

**Comment by apneadiving** [comment]
shit, please check https://github.com/apneadiving/apneadiving.github.io/commit/55ab1705a49bfa19d589ce3518e71a27b605f912
First attempt to get scripts since google code doesnt provide them anymore.

**Comment by lucasgerard** [comment]
yeah, it seems that google code is not providing them anymore. Any chance you got a fix for Marker With Label library?

**Comment by donBigote** [comment]
I am getting the same error. Should I wait for you guys to push a fix?

**Comment by carnash-oz** [comment]
replace dead links works, thx ( save my life and work XD )

**Comment by RoccStar** [comment]
Yup worked for me too. Thanks for the quick update!

**Comment by apneadiving** [comment]
I've updated the doc, @donBigote  there is nothing more I can do.
@lucasgerard  this should do the trick: https://cdn.rawgit.com/jesstelford/node-MarkerWithLabel/master/index.js

**Comment by lucasgerard** [comment]
Yeeeah, thx ;)

**Comment by apneadiving** [comment]
Thanks @RoccStar for reporting :)

**Comment by donBigote** [comment]
It's up and running again. Thanks for the quick response! I love this gem and appreciate all the work you put into it.

**Comment by mvaragnat** [comment]
Thanks @apneadiving for the quick fix
