### ISSUE TITLE
Google maps aren't displayed anymore (missing resources)

### ISSUE THREAD

**Issue by umberto** [apneadiving/Google-Maps-for-Rails#514]
The following resources aren't available anymore:

[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (markerclusterer_packed.js, line 0)

[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (infobox_packed.js, line 0)

The corresponding urls are:

http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js
https://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js

Maybe because they moved to Github?

**Comment by apneadiving** [comment]
Hi, indeed, those are not available anymore :) I've updated the doc yesterday.

**Comment by umberto** [comment]
Thanks a lot! I wasn't aware of that. Everything is ok again.

**Comment by printercu** [comment]
I've made gist with instructions https://gist.github.com/printercu/c4a02b8972ad76b6331b51b98c4b87a5

**Comment by ThomasCelen** [comment]
Hi, can someone please give me some steps on how to fix this issue. I'm getting completely lost in the gist..

**Comment by apneadiving** [comment]
@ThomasCelen just follow the updated readme :)

**Comment by ThomasCelen** [comment]
Awesome, works like a charm.
However, I've now also received JS error messages regarding the API:
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
util.js:220 Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
util.js:220 Google Maps API warning: InvalidClientId https://developers.google.com/maps/documentation/javascript/error-messages#invalid-client-id
util.js:220 Google Maps API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key

Any reason why I'm getting the errors now and not before?

**Comment by yuchunc** [comment]
New readme solved my issue! Thank you! = )
