### ISSUE TITLE
Using older version of Gmaps4rails with v3.23 Gmaps API?

### ISSUE THREAD

**Issue by shakycode** [apneadiving/Google-Maps-for-Rails#517]
I'm stuck on an old Rails 3.2.22 legacy app with gmaps4rails 2.0.0.pre (yes I know it's older).  Since the API being used in this version is broken, is there any way that I can keep this gem in place and somehow use the v3.23 API?  All of my maps stopped working when they deprecated v2 API a while back.

I can upgrade to the latest version I guess but I have everything setup how I like it and would like to see if I can somehow get around having to upgrade and rewrite.

**Comment by apneadiving** [comment]
You could monkey patch [this](https://github.com/apneadiving/Google-Maps-for-Rails/blob/v2.0.pre/lib/gmaps4rails/view_helper.rb#L64-L76) to replace with the proper links.

I wont push a new version on rubygems for this, sorry
