### ISSUE TITLE
broken map

### ISSUE THREAD

**Issue by stefkas** [apneadiving/Google-Maps-for-Rails#532]
I use **gmaps4rails 1.5.7** in my Rails 3.2.19 app, so the user can select his location. In the general administrator's page, the map loads without any problem and I (the admin) can select or fix the location of the user. But on the user's edit page, with exactly the same code as the page of the administrator, I have a broken map like this:

<img width="587" alt="broken map with gmaps4rails" src="https://cloud.githubusercontent.com/assets/2665812/18723110/0a082502-8040-11e6-9e10-8729a795313a.png">

No matter if I drag the map, the visible part, is only a small piece of the given area. It is crazy as I have exactly the same code in both cases.

Do you have any idea for this?

**Comment by apneadiving** [comment]
Are you sure the div containing the map is visible whenever the js code to create the map is executed?

**Comment by stefkas** [comment]
You are absolutely right! 
I was digging into js code or css, but the problem was the fact that the map was loaded into a different hidden tab, not the main active.

Thank you for your help!
