### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of null

### ISSUE THREAD

**Issue by arun1595** [apneadiving/Google-Maps-for-Rails#534]
I followed the steps provided in the documentation but I am unable to get it working. I am getting the following error message
```
Uncaught TypeError: Cannot read property 'firstChild' of null
```
in the `https://maps.google.com/maps/api/js` script. From the error message, what I understand is that the script is trying to call the method `firstChild` method on a `Node` object but its `null`.

I have no idea how to solve this. Any help would be appreciated.

**Comment by arun1595** [comment]
My bad. I was trying to load the script before DOM was loaded. I moved the script to the end of the `body` and things went fine. 

I'll close the issue as it was mistake from my side.

**Comment by Robiullah2244** [comment]
I was trying to load the DOM  before the script was loaded. But I didn't come to the solution. Sometimes Script is loaded before dom although Script was written at the end. For that, you can load Script with defer.

<script defer src="https://maps.googleapis.com/maps/api/js?key=Your_Google_Api_Key&libraries&callback=initMap">
</script>

![difer](https://user-images.githubusercontent.com/33126665/51981071-18cc3b00-24bc-11e9-938a-c61be03d967a.PNG)

**Comment by educhip** [comment]
> My bad. I was trying to load the script before the DOM was loaded. I moved the script to the end of `body` and it worked fine.
> 
I have been 2 days trying delete cache for several methods! but the solution was this! Thanks mate ;-)
