### ISSUE TITLE
[FAQ] Google Maps APIs support

### ISSUE THREAD

**Issue by kirantpatil** [apneadiving/Google-Maps-for-Rails#539]
Hi,

Does Google-Maps-for-Rails supports all of below APIs.

    Directions API
    Distance Matrix API
    Elevation API
    Geocoding API
    Time Zone API
    Roads API
    Places API
    Static Maps API

Thanks.

**Comment by apneadiving** [comment]
I'm unsure what you mean by `support`, but the gem doesnt interact with them.
